# Generated by Django 6.0.2 on 2026-02-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('entraineur', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('numero_habituel', models.IntegerField(default=0)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectif', to='gestion.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_match', models.DateTimeField(auto_now_add=True)),
                ('lieu', models.CharField(default='Piscine', max_length=100)),
                ('nom_equipe_domicile', models.CharField(max_length=100)),
                ('nom_equipe_exterieur', models.CharField(max_length=100)),
                ('duree_periode', models.IntegerField(default=8)),
                ('temps_possession', models.IntegerField(default=28)),
                ('temps_exclusion', models.IntegerField(default=18)),
                ('nb_temps_mort', models.IntegerField(default=2)),
                ('score_domicile', models.IntegerField(default=0)),
                ('score_exterieur', models.IntegerField(default=0)),
                ('periode_actuelle', models.IntegerField(default=1)),
                ('compo_validee', models.BooleanField(default=False)),
                ('equipe_domicile_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_dom', to='gestion.equipe')),
                ('equipe_exterieur_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_ext', to='gestion.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bonnet', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('equipe_concernee', models.CharField(max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gestion.match')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('BUT', 'But'), ('EXCL', 'Exclusion'), ('TM', 'Temps Mort'), ('PERIODE', 'Fin Période')], max_length=10)),
                ('temps_jeu_chrono', models.CharField(default='00:00', max_length=8)),
                ('periode', models.IntegerField(default=1)),
                ('equipe_attribuee', models.CharField(choices=[('DOM', 'Domicile'), ('EXT', 'Extérieur')], max_length=10, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.match')),
                ('joueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.participation')),
            ],
        ),
    ]
