# Generated by Django 6.0.2 on 2026-02-04 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Règlement 2026', max_length=50)),
                ('temps_possession', models.IntegerField(default=28, help_text='Ex: 28 secondes')),
                ('temps_exclusion', models.IntegerField(default=18, help_text='Ex: 18 secondes')),
                ('duree_periodes', models.IntegerField(default=8, help_text="Durée d'un quart-temps en minutes")),
                ('nb_periodes', models.IntegerField(default=4, help_text='Nombre de périodes par match')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du club')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('couleur_bonnet', models.CharField(choices=[('BLANC', 'Blanc'), ('BLEU', 'Bleu/Noir')], default='BLANC', max_length=20)),
                ('entraineur_principal', models.CharField(blank=True, max_length=100)),
                ('entraineur_adjoint', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('licence_iuf', models.CharField(max_length=20, unique=True, verbose_name='Numéro de Licence (IUF)')),
                ('annee_naissance', models.IntegerField(verbose_name='Année de naissance')),
                ('numero_habituel', models.IntegerField(default=0)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectif', to='gestion.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_match', models.DateField(default=django.utils.timezone.now)),
                ('heure_match', models.TimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(default='Piscine Paul Boyrie', max_length=100)),
                ('competition', models.CharField(default='Championnat N3 Occitanie', max_length=100)),
                ('score_domicile', models.IntegerField(default=0)),
                ('score_exterieur', models.IntegerField(default=0)),
                ('est_termine', models.BooleanField(default=False)),
                ('periode_actuelle', models.IntegerField(default=1)),
                ('arbitre_1', models.CharField(blank=True, max_length=100)),
                ('arbitre_2', models.CharField(blank=True, max_length=100)),
                ('delegue_ffn', models.CharField(blank=True, max_length=100)),
                ('secretaire', models.CharField(default='Étudiant 1', max_length=100)),
                ('chronometreur', models.CharField(default='Étudiant 2', max_length=100)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.configuration')),
                ('equipe_domicile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchs_domicile', to='gestion.equipe')),
                ('equipe_exterieur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchs_exterieur', to='gestion.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bonnet', models.IntegerField(help_text='Numéro 1 à 13 pour ce match')),
                ('est_capitaine', models.BooleanField(default=False)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.joueur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feuille_de_match', to='gestion.match')),
            ],
            options={
                'ordering': ['numero_bonnet'],
                'unique_together': {('match', 'numero_bonnet', 'joueur')},
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('BUT', 'But'), ('EXCL', 'Exclusion (E)'), ('PENALTY', 'Penalty (P)'), ('EDA', 'Exclusion Définitive (EDA)'), ('TM', 'Temps Mort'), ('CARTON_J', 'Carton Jaune'), ('CARTON_R', 'Carton Rouge')], max_length=10)),
                ('heure_creation', models.DateTimeField(auto_now_add=True)),
                ('temps_jeu_chrono', models.CharField(help_text='Ex: 06:24', max_length=8)),
                ('periode', models.IntegerField(default=1)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.equipe')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='gestion.match')),
                ('joueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.participation')),
            ],
        ),
    ]
