# Generated by Django 6.0.2 on 2026-02-05 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='periode',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='temps_jeu_chrono',
        ),
        migrations.AddField(
            model_name='evenement',
            name='chrono_match',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='evenement',
            name='heure_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='chrono_en_cours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='dernier_top_chrono',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='temps_restant',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='participation',
            name='est_exclu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participation',
            name='est_exclu_definitif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participation',
            name='fin_exclusion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='nb_fautes_personnelles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='equipe_attribuee',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_action',
            field=models.CharField(choices=[('BUT', 'But'), ('EXCL', 'Exclusion Temporaire'), ('EDA', 'Exclusion Définitive'), ('TM', 'Temps Mort')], max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='temps_exclusion',
            field=models.IntegerField(default=20),
        ),
    ]
