# Generated by Django 6.0.2 on 2026-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_evenement_periode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duree_exclusion',
            field=models.IntegerField(default=20, help_text='En secondes'),
        ),
        migrations.AddField(
            model_name='match',
            name='max_fautes_perso',
            field=models.IntegerField(default=3, help_text='Nombre de fautes avant exclusion définitive'),
        ),
        migrations.AddField(
            model_name='match',
            name='nb_periodes',
            field=models.IntegerField(default=4, help_text='Nombre de périodes'),
        ),
        migrations.AddField(
            model_name='match',
            name='nb_remplacants',
            field=models.IntegerField(default=6, help_text='Nombre de remplaçants max'),
        ),
        migrations.AddField(
            model_name='match',
            name='nb_temps_morts',
            field=models.IntegerField(default=2, help_text='Par équipe'),
        ),
        migrations.AlterField(
            model_name='match',
            name='duree_periode',
            field=models.IntegerField(default=8, help_text="Durée d'une période en minutes (ex: 8)"),
        ),
        migrations.AlterField(
            model_name='match',
            name='temps_possession',
            field=models.IntegerField(default=30, help_text="Temps d'attaque en secondes"),
        ),
    ]
