# Generated by Django 6.0.2 on 2026-02-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_match_duree_exclusion_match_max_fautes_perso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ['heure_creation']},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['equipe_concernee', 'numero_bonnet']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='nb_temps_mort',
        ),
        migrations.RemoveField(
            model_name='match',
            name='temps_exclusion',
        ),
        migrations.AddField(
            model_name='evenement',
            name='periode',
            field=models.IntegerField(default=1, help_text="Période du match lors de l'action"),
        ),
        migrations.AddField(
            model_name='evenement',
            name='score_dom_apres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evenement',
            name='score_ext_apres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='annee_naissance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joueur',
            name='numero_licence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='arbitre1_iuf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='arbitre1_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='arbitre2_iuf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='arbitre2_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='chrono_iuf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='chrono_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.CharField(blank=True, help_text='Intitulé de la compétition (ex: Championnat de France N3)', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='couleur_bonnet_dom',
            field=models.CharField(default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='couleur_bonnet_ext',
            field=models.CharField(default='BLEU', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='delegue_dom_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='delegue_ext_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='delegue_ffn_iuf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='delegue_ffn_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='entraineur_adj_dom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='entraineur_adj_ext',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='entraineur_dom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='entraineur_ext',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='heure_debut',
            field=models.TimeField(blank=True, help_text='Heure de début du match (HH:MM)', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='juge_but1_iuf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='juge_but1_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='juge_but2_iuf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='juge_but2_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='secretaire_iuf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='secretaire_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='suppleant_dom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='suppleant_ext',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participation',
            name='annee_naissance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='numero_licence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='chrono_match',
            field=models.CharField(default='00:00', help_text="Temps affiché au moment de l'action", max_length=10),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='equipe_attribuee',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='joueur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='gestion.participation'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='gestion.match'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_action',
            field=models.CharField(choices=[('BUT', 'But'), ('FAUTE', 'Faute ordinaire'), ('EXCL', 'Exclusion temporaire'), ('EDA', 'Exclusion définitive'), ('PENALTY', 'Penalty'), ('TM', 'Temps mort')], max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='duree_exclusion',
            field=models.IntegerField(default=20, help_text="Durée d'exclusion temporaire en secondes"),
        ),
        migrations.AlterField(
            model_name='match',
            name='duree_periode',
            field=models.IntegerField(default=8, help_text="Durée d'une période en minutes"),
        ),
        migrations.AlterField(
            model_name='match',
            name='nb_temps_morts',
            field=models.IntegerField(default=2, help_text='Nombre de temps morts par équipe'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='equipe_concernee',
            field=models.CharField(choices=[('DOM', 'Domicile'), ('EXT', 'Extérieur')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('match', 'equipe_concernee', 'numero_bonnet')},
        ),
        migrations.CreateModel(
            name='ScorePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periode', models.IntegerField()),
                ('score_dom', models.IntegerField(default=0)),
                ('score_ext', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_periodes', to='gestion.match')),
            ],
            options={
                'ordering': ['numero_periode'],
                'unique_together': {('match', 'numero_periode')},
            },
        ),
    ]
