# Generated by Django 6.0.4 on 2026-05-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_evenement_options_alter_participation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='logo_dom',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='match',
            name='logo_ext',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='sponsors/')),
                ('ordre', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='gestion.match')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
