# Generated by Django 6.0.4 on 2026-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_add_logos_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='shot_en_cours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='shot_restant',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='match',
            name='shot_top',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
