# Generated by Django 6.0.4 on 2026-05-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_match_shot_en_cours_match_shot_restant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='est_sur_terrain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_action',
            field=models.CharField(choices=[('B', 'But'), ('E', 'Exclusion temporaire'), ('P', 'Penalty'), ('EDA', 'Exclusion définitive'), ('EDAP', 'Exclusion déf. après 4 min'), ('A', 'Accident'), ('R', 'Réclamation'), ('TM', 'Temps mort'), ('CJ€', 'Carton Jaune Équipe'), ('CR', 'Carton Rouge')], max_length=10),
        ),
    ]
