# Generated by Django 6.0.4 on 2026-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_match_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scoreboard_sponsor_scale',
            field=models.IntegerField(default=100, help_text='Taille des images sponsors en % (40-200)'),
        ),
    ]
